language: objective-c
before_install:
    - brew update
    - brew install xctool
script: xctool -workspace Funkt.xcworkspace -scheme FunktTests -sdk iphonesimulator -configuration Debug clean build test
